### PR TITLE
Updating with new features and notes from class! (practicing my githu…

### PR DESCRIPTION
**Pull request by biubird**
…b skills)

### CODE REVIEW

**Comment by TEnders64** [comment]
nice Heather!  I didn't push my changes from yesterday's demo so thank you for forking it and making your own changes!  I'll merge your code.

**Comment by biubird** [comment]
Woohoo!! :)

**Comment by TEnders64** [comment]
we got some merge conflicts but it's forcing me to do some github work as well

**Comment by biubird** [comment]
Ok, we can talk briefly tomorrow in our session about it just so I know if
I need to do something different?

**Pull request merged**
